// This code was generated by: 
// https://github.com/recolude/swagger-unity-codegen
// Issues and PRs welcome :)

using UnityEngine;
using UnityEngine.Networking;
using System.Collections;

namespace Recolude
{

    [System.Serializable]
    public class ProtobufAny
    {

        public string type_url;

        public string value;

    }

    [System.Serializable]
    public class Resourcesv1License
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public string description;

        public V1LicenseDetails details;

        [SerializeField]
        private string end_of_period;

        public System.DateTime EndOfPeriod { get => System.DateTime.Parse(end_of_period); }

        public string id;

        public string name;

        public string status;

        [SerializeField]
        private string updated_at;

        public System.DateTime UpdatedAt { get => System.DateTime.Parse(updated_at); }

    }

    [System.Serializable]
    public class RuntimeError
    {

        public int code;

        public ProtobufAny[] details;

        public string error;

        public string message;

    }

    [System.Serializable]
    public class V1ApiKey
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        [SerializeField]
        private string deleted_at;

        public System.DateTime DeletedAt { get => System.DateTime.Parse(deleted_at); }

        public string description;

        public string id;

        public string name;

        public V1Permission[] permissions;

        public V1Project project;

        public string project_id;

        public string token;

        [SerializeField]
        private string updated_at;

        public System.DateTime UpdatedAt { get => System.DateTime.Parse(updated_at); }

    }

    [System.Serializable]
    public class V1CustomEventCapture
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public string id;

        public string name;

        public V1Subject subject;

        public V1MetadataTag[] tags;

        public float time;

        public string trackable_id;

        public string trackable_type;

    }

    [System.Serializable]
    public class V1Customer
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public string id;

        public string stripe_customer_id;

    }

    [System.Serializable]
    public class V1DevKey
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public string id;

        public V1Person person;

        public string person_id;

        public string token;

        [SerializeField]
        private string updated_at;

        public System.DateTime UpdatedAt { get => System.DateTime.Parse(updated_at); }

    }

    public enum V1EnumLifeCycle
    {
        LC_UNKNOWN = 0,
        LC_START = 1,
        LC_ENABLE = 2,
        LC_DISABLE = 3,
        LC_DESTROY = 4
    }

    public enum V1EnumPermissionScope
    {
        PS_UNKNOWN = 0,
        PS_GLOBAL = 1,
        PS_ORGANIZATION = 2,
        PS_PROJECT = 3
    }

    public enum V1EnumProjectType
    {
        PT_UNKONWN = 0,
        PT_PERSONAL = 1,
        PT_ORGANIZATION = 2
    }

    public enum V1EnumUserState
    {
        US_UNKNOWN = 0,
        US_UNCONFIRMED = 1,
        US_ENABLED = 2,
        US_DISABLED = 3
    }

    public enum V1EnumVisibility
    {
        V_UNKOWN = 0,
        V_PUBLIC = 1,
        V_PRIVATE = 2,
        V_PROTECTED = 3
    }

    [System.Serializable]
    public class V1LicenseDetails
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public string id;

        public string stripeSubscriptionId;

        public string stripe_customer_id;

        public string[] stripe_subscription_item_ids;

        [SerializeField]
        private string updated_at;

        public System.DateTime UpdatedAt { get => System.DateTime.Parse(updated_at); }

    }

    [System.Serializable]
    public class V1LifeCycleEventCapture
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public string id;

        public V1Subject subject;

        public string subjectId;

        public float time;

        public V1EnumLifeCycle type;

    }

    [System.Serializable]
    public class V1ListRecordingsRequest
    {

        public bool deleted;

        public int limit;

        public int max_date;

        public float max_duration;

        public int max_events;

        public int max_subjects;

        public int min_date;

        public float min_duration;

        public int min_events;

        public int min_subjects;

        public string name;

        public string[] names;

        public int offset;

        public string order_by;

        public string organization_id;

        public string[] organization_ids;

        public string project_id;

        public string[] project_ids;

        public V1EnumVisibility visibility;

    }

    [System.Serializable]
    public class V1MetadataTag
    {

        public string content;

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public string id;

        public string name;

        public string trackable_id;

        public string trackable_type;

    }

    [System.Serializable]
    public class V1Organization
    {

        public int available_trials;

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        [SerializeField]
        private string deleted_at;

        public System.DateTime DeletedAt { get => System.DateTime.Parse(deleted_at); }

        public string display_name;

        public string id;

        public Resourcesv1License license;

        public string license_id;

        public string name;

        public V1Permission[] permissions;

        public V1Person[] persons;

        public V1Project[] projects;

        [SerializeField]
        private string updated_at;

        public System.DateTime UpdatedAt { get => System.DateTime.Parse(updated_at); }

    }

    [System.Serializable]
    public class V1Permission
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public string id;

        public V1SecurityRole security_role;

        public string security_role_id;

        public string trackable_entity_id;

        public string trackable_entity_type;

        public string trackable_group_id;

        public string trackable_group_type;

        [SerializeField]
        private string updated_at;

        public System.DateTime UpdatedAt { get => System.DateTime.Parse(updated_at); }

    }

    [System.Serializable]
    public class V1Person
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public V1Customer customer;

        public string customer_id;

        [SerializeField]
        private string deleted_at;

        public System.DateTime DeletedAt { get => System.DateTime.Parse(deleted_at); }

        public V1DevKey dev_key;

        public string email;

        public string id;

        public V1Organization[] organizations;

        public V1Permission[] permissions;

        public V1Project[] projects;

        public V1EnumUserState state;

        public string sub;

        [SerializeField]
        private string updated_at;

        public System.DateTime UpdatedAt { get => System.DateTime.Parse(updated_at); }

        public string username;

    }

    [System.Serializable]
    public class V1PositionCapture
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public string id;

        public V1Subject subject;

        public string subjectId;

        public float time;

        public float x;

        public float y;

        public float z;

    }

    [System.Serializable]
    public class V1Project
    {

        public V1ApiKey[] api_keys;

        public string classification;

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        [SerializeField]
        private string deleted_at;

        public System.DateTime DeletedAt { get => System.DateTime.Parse(deleted_at); }

        public string description;

        public string id;

        public Resourcesv1License license;

        public string license_id;

        public string name;

        public V1Organization organization;

        public string organization_id;

        public V1Permission[] permissions;

        public V1Person[] persons;

        public V1Recording[] recordings;

        public V1EnumProjectType type;

        [SerializeField]
        private string updated_at;

        public System.DateTime UpdatedAt { get => System.DateTime.Parse(updated_at); }

        public V1EnumVisibility visibility;

    }

    [System.Serializable]
    public class V1Recording
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public V1CustomEventCapture[] custom_events;

        [SerializeField]
        private string deleted_at;

        public System.DateTime DeletedAt { get => System.DateTime.Parse(deleted_at); }

        public string id;

        public string name;

        public V1Project project;

        public string project_id;

        public V1Subject[] subjects;

        public V1RecordingSummary summary;

        public V1MetadataTag[] tags;

        [SerializeField]
        private string updated_at;

        public System.DateTime UpdatedAt { get => System.DateTime.Parse(updated_at); }

        public V1EnumVisibility visibility;

    }

    [System.Serializable]
    public class V1RecordingResponse
    {

        public V1Recording recording;

    }

    [System.Serializable]
    public class V1RecordingSummary
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public int custom_events;

        public double duration;

        public string id;

        public string project_id;

        public int subjects;

        [SerializeField]
        private string uploaded_at;

        public System.DateTime UploadedAt { get => System.DateTime.Parse(uploaded_at); }

    }

    [System.Serializable]
    public class V1RecordingsResponse
    {

        public V1Recording[] recordings;

        public V1ListRecordingsRequest request;

        public int total_size;

    }

    [System.Serializable]
    public class V1RotationCapture
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public string id;

        public V1Subject subject;

        public string subjectId;

        public float time;

        public float x;

        public float y;

        public float z;

    }

    [System.Serializable]
    public class V1SecurityGrant
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public string description;

        public string id;

        public string name;

        public V1EnumPermissionScope scope;

        [SerializeField]
        private string updated_at;

        public System.DateTime UpdatedAt { get => System.DateTime.Parse(updated_at); }

    }

    [System.Serializable]
    public class V1SecurityRole
    {

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public string description;

        public string id;

        public string name;

        public V1EnumPermissionScope scope;

        public V1SecurityGrant[] security_grants;

        [SerializeField]
        private string updated_at;

        public System.DateTime UpdatedAt { get => System.DateTime.Parse(updated_at); }

    }

    [System.Serializable]
    public class V1Subject
    {

        public V1PositionCapture[] captured_positions;

        public V1RotationCapture[] captured_rotations;

        [SerializeField]
        private string created_at;

        public System.DateTime CreatedAt { get => System.DateTime.Parse(created_at); }

        public V1CustomEventCapture[] custom_events;

        public string id;

        public V1LifeCycleEventCapture[] life_cycle_events;

        public int local_id;

        public string name;

        public V1Recording recording;

        public string recording_id;

        public V1MetadataTag[] tags;

    }

}